# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='reserved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=8, max_digits=6),
        ),
    ]
